# Generated by Django 3.2.8 on 2021-11-15 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_appeared', models.DateTimeField(default=django.utils.timezone.now, unique=True, verbose_name='Время появления происшествия')),
                ('time_solved', models.DateTimeField(blank=True, null=True, verbose_name='Время решения происшествия')),
                ('post', models.IntegerField(verbose_name='Пост с происшествием')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание происшествия')),
            ],
        ),
        migrations.CreateModel(
            name='AccidentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Класс происшествия')),
                ('name', models.CharField(max_length=64, verbose_name='Название класса происшествия')),
            ],
        ),
        migrations.CreateModel(
            name='AccidentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_changed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время внесения изменений')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание происшествия')),
                ('accident', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accident_history', to='accident.accident')),
                ('accident_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accident.accidentclass')),
            ],
        ),
        migrations.AddField(
            model_name='accident',
            name='accident_class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accident.accidentclass'),
        ),
        migrations.AddField(
            model_name='accident',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to=settings.AUTH_USER_MODEL),
        ),
    ]
