# Generated by Django 3.2.8 on 2021-11-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accident',
            old_name='post',
            new_name='posts_block',
        ),
    ]
