# Generated by Django 3.2.8 on 2021-10-20 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Класс происшествия')),
                ('name', models.CharField(max_length=64, verbose_name='Название класса происшествия')),
            ],
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True, verbose_name='Время создания инцидента')),
                ('post', models.IntegerField(verbose_name='Пост с происшествием')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание происшествия')),
                ('accident_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreAPI.accidentclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
