# Generated by Django 3.2.8 on 2021-10-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConveyorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.IntegerField(verbose_name='Номер поста')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Success'), (3, 'Error')], verbose_name='Статус поста')),
            ],
        ),
    ]
