# Generated by Django 3.2.8 on 2021-10-22 02:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreAPI', '0002_conveyorstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='accident',
            name='time_appeared',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 2, 23, 49, 668800), verbose_name='Время создания инцидента'),
        ),
        migrations.AddField(
            model_name='accident',
            name='time_solved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время создания инцидента'),
        ),
        migrations.CreateModel(
            name='AccidentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_appeared', models.DateTimeField(verbose_name='Время создания инцидента')),
                ('time_solved', models.DateTimeField(blank=True, null=True, verbose_name='Время создания инцидента')),
                ('post', models.IntegerField(verbose_name='Пост с происшествием')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание происшествия')),
                ('accident', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreAPI.accident')),
                ('accident_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreAPI.accidentclass')),
            ],
        ),
    ]
