# Generated by Django 3.2.8 on 2021-10-22 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreAPI', '0007_alter_accident_time_appeared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='time_appeared',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания инцидента'),
        ),
    ]
