# Generated by Django 3.2.8 on 2021-10-22 04:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreAPI', '0008_alter_accident_time_appeared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidenthistory',
            name='post',
        ),
        migrations.RemoveField(
            model_name='accidenthistory',
            name='time_appeared',
        ),
        migrations.RemoveField(
            model_name='accidenthistory',
            name='time_solved',
        ),
        migrations.AlterField(
            model_name='accident',
            name='accident_class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreAPI.accidentclass'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='time_appeared',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время появления происшествия'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='time_solved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время решения происшествия'),
        ),
    ]
