# Generated by Django 3.2.8 on 2021-10-22 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreAPI', '0009_auto_20211022_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='time_appeared',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True, verbose_name='Время появления происшествия'),
        ),
    ]
