# Generated by Django 3.2.8 on 2021-10-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreAPI', '0011_alter_accident_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidenthistory',
            name='accident',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accident_history', to='coreAPI.accident'),
        ),
    ]
