# Generated by Django 3.2.8 on 2021-10-23 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreAPI', '0012_alter_accidenthistory_accident'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidenthistory',
            name='time_changed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время внесения изменений'),
        ),
    ]
