# Generated by Django 3.2.8 on 2021-10-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreAPI', '0013_accidenthistory_time_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveyorstate',
            name='status',
            field=models.CharField(default='success', max_length=12, verbose_name='Статус поста'),
        ),
    ]
