# Generated by Django 3.2.8 on 2021-10-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, null=True, verbose_name='First Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='some description')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
