# Generated by Django 3.2.8 on 2021-10-20 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_created=True, verbose_name='Время создания инцидента')),
                ('post', models.IntegerField(max_length=24, verbose_name='Пост с происшествием')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание происшествия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccidentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=10, verbose_name='Класс происшествия')),
                ('name', models.CharField(max_length=64, verbose_name='Название класса происшествия')),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
