# Generated by Django 3.2.8 on 2021-10-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20211020_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='accidentClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.accidentclass'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='post',
            field=models.IntegerField(verbose_name='Пост с происшествием'),
        ),
        migrations.AlterField(
            model_name='accidentclass',
            name='number',
            field=models.IntegerField(verbose_name='Класс происшествия'),
        ),
    ]
