# Generated by Django 3.2.8 on 2021-10-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20211020_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accident',
            old_name='accidentClass',
            new_name='accident_class',
        ),
        migrations.RenameField(
            model_name='accident',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
